### ISSUE TITLE
"substrate-api-client" is no longer buildable

### ISSUE THREAD

**Issue by dingxiangfei2009** [scs/substrate-api-client#166]
Due to upstream changes in `frame-metadata`, this library is no longer usable if one includes it in a fresh project.

To reproduce the issue, simply `cargo init newtest` and add the following to `Cargo.toml`.
```toml
[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
default-features = false
features = ["std"]
```

`frame-metadata` has been moved to `https://github.com/paritytech/frame-metadata` and is available from `crates.io`.
However, there has been a great amount of API changes.
Maybe we need to *pin to a specific git commit* of `substrate` for now.
